### ISSUE TITLE
Add "camelize" function

### ISSUE THREAD

**Issue by jessielaf** [adenh93/django-typomatic#18]
I am using this module [djangorestframework-camel-case](https://pypi.org/project/djangorestframework-camel-case/). With this all of the fields change to camel casing. I was wondering if that could also be implemented in this project? Are you open for pr's?

**Comment by jessielaf** [comment]
If I am correct I can just edit the `__process_field` function. Is this correct?

**Comment by adenh93** [comment]
@jessielaf If it can be implemented as an optional feature when generating the fields, then I would be more than happy to accept a PR 👌

**Comment by jessielaf** [comment]
@adenh93 I opened #19 !

**Comment by adenh93** [comment]
@jessielaf Released v1.5.0 just now with your feature included, nice addition! 👍
