### ISSUE TITLE
Remove 'Serializer' from the TS Interface output

### ISSUE THREAD

**Issue by adenh93** [adenh93/django-typomatic#2]
e.g. UserFilterSerializer should simply become UserFilter

**Comment by fjbardelli** [comment]
Hello, This es possible?

**Comment by adenh93** [comment]
Hi @fjbardelli,

Just added an optional argument to get_ts and generate_ts called 'exclude_serializer_output'.

Passing true should trim 'Serializer' from the end of the output.

Publishing now,

Thanks 👍

**Comment by adenh93** [comment]
Hi @fjbardelli,

v1.4.0 is now published on pypi 👍

**Comment by fjbardelli** [comment]
Thaks
