### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hhaidar** [adenh93/django-typomatic#20]
Hey!

Hope you're doing well. Is there any chance you'd be willing to relicense (or perhaps dual license) your package to MIT/BSD? There's a bit of an aversion at my company to using GPL on certain projects so it'd help greatly with buy in.

Thank you

**Comment by adenh93** [comment]
Hi @hhaidar, absolutely!

**Comment by adenh93** [comment]
Hi @hhaidar, done! 👍 
It was a mistake originally choosing the GPL template, so thank you for pointing that out 👌
