### ISSUE TITLE
serializers.ChoiceField options getting converted to 'any'

### ISSUE THREAD

**Issue by dkappBTO** [adenh93/django-typomatic#21]
Given the following code:
`from django.utils.translation import gettext_lazy as _`
`from rest_framework import serializers`
`from django.db import models`

`@ts_interface()` 
 `class ActionType(models.TextChoices):`
    `     ACTION1 = "Action1", _("Action1")`
    `  ACTION2 = "Action2", _("Action2")`

`@ts_interface()`
`class ActionSerializer(serializers.Serializer[Any]):`
    `action = serializers.ChoiceField(choices=ActionType.choices)`

The output of conversion is:
`export interface ActionSerializer {`
    `action: any;` -> wrong!
`}`

I would expect 'action' to be a union class of `'Action1' | 'Action2'` or `'ACTION1' | 'ACTION2'`. Am I using django-typomatic incorrectly or is this simply a limitation of the library?

Thanks!

**Comment by adenh93** [comment]
Hi @dkappBTO, you're right, it's currently a limitation of the library.
I'll try to add support for ChoiceField right now :+1:

**Comment by adenh93** [comment]
Hi @dkappBTO. Done! :+1: 
Will prepare a release and let you know when you can update.

**Comment by adenh93** [comment]
@dkappBTO Published v1.6.0. Thanks for the suggestion, will close this one now! :ok_hand:

**Comment by adenh93** [comment]
Please pull the latest version 1.6.1, as I've added a couple fixes since publishing this feature.

**Comment by dkappBTO** [comment]
Awesome! Thanks for the quick turn around :)
