### ISSUE TITLE
Should not use choices for PrimaryKeyRelatedField 

### ISSUE THREAD

**Issue by jasongi** [adenh93/django-typomatic#22]
Great library, has saved me a lot of time!

One issue I had is that it would use choices for `PrimaryKeyRelatedField` - populating the types with a list of every possible ID in the database. This isn't desirable because there's no reason you should be referencing database IDs in your frontend code, and even if you were, it's likely your local dev environment where you're writing this will be out of sync with production.

My workaround to this was to do this in my management command where I generate the ts:

```
from django_typomatic import get_ts, ts_field
from rest_framework import serializers

ts_field("number")(serializers.PrimaryKeyRelatedField)
```

A more permanent solution could be to add an extra elif clause before the choices check to specifically check if it is a PrimaryKeyRelatedField, and then somehow figure out the type of the pk for that field (DRF doesn't store this anywhere I can see). Alternatively we could use `number | string` as the type or just `number` since that's how Django automatically generates IDs.

**Comment by adenh93** [comment]
Hi @jasongi, sorry for the late response!

Good spot. I've added the change you've suggested now, and I've published v1.6.2.

Thank you!
