### ISSUE TITLE
TypeError when used with Permission model

### ISSUE THREAD

**Issue by BradWells** [adenh93/django-typomatic#39]
I really like this library for copying and pasting types into my UI (I do a find/replace for 'Serializer' and replace it with nothing and commit it to my UI codebase).

However, I'm running into a problem with the builtin Permissions model.

```
# serializers.py
from django.contrib.auth.models import Permission
from django_typomatic import ts_interface
from rest_framework.serializers import ModelSerializer


@ts_interface
class PermissionSerializer(ModelSerializer):
    class Meta:
        model = Permission
        fields = '__all__'
```

```
# views.py
@api_view(["GET"])
@permission_classes((permissions.IsAuthenticated,))
def get_all_permissions_for_groups(request):
    all_permissions = Permission.objects \
        .prefetch_related('group_set', 'content_type') \
        .filter(group__user=request.user
                )
    serializer = PermissionSerializer(all_permissions, many=True)
    return JsonResponse(serializer.data, safe=False)
```

Expected output:
```
[]
# or list of Permission objects of the groups I am part of
```

Actual output:
```
<SNIP>

  File "C:\Users\bradl\lji\projects\childlight_django\app\rest\permissions\views.py", line 34, in get_all_permissions
    serializer = PermissionSerializer(all_permissions, many=True)
TypeError: decorator() got an unexpected keyword argument 'many'
```

commenting out the @ts_interface annotation results in the expected output

**Comment by bigpe** [comment]
@BradWells 

Use is this way, instead decorator on class

```python
class PermissionSerializer(ModelSerializer):
    class Meta:
        model = Permission
        fields = '__all__'

ts_interface()(PermissionSerializer)
generate_ts('permission.ts')
```

You can also use the newer and preferred generation method - CLI (Django managment comand)
At first need add django_typomatic to INSTALLED_APPS

**Comment by BradWells** [comment]
Thanks for the reply! That worked! 

P.S. I did try to use the new serializer, but it did not work because of how my codebase is structured, I [opened another issue](https://github.com/adenh93/django-typomatic/issues/44). 
P.P.S. I didn't know that you could pass trim=True to get_ts(), you should put that in the docs!
