### ISSUE TITLE
KeyError: 'default' | elif field_type in __field_mappings[context]:

### ISSUE THREAD

**Issue by yariv-tperson** [adenh93/django-typomatic#4]
Had a problem in `__process_field`: `elif field_type in __field_mappings[context]:`
it was expecting the key 'default' exist in `__field_mappings`, but `__field_mappings` was populated only in `ts_field.decorator` which I was not using.

Solved it by adding the same population logic in `ts_interface.decorator`:
```python
    def decorator(cls):
        if issubclass(cls, serializers.Serializer):
            if context not in __field_mappings:
                __field_mappings[context] = dict()
            if context not in __serializers:
                __serializers[context] = []
            __serializers[context].append(cls)
```

and it worked :)

**Comment by adenh93** [comment]
Resolved in a PR by @ptevans 👍
