### ISSUE TITLE
Release 2.5.0 to pypi

### ISSUE THREAD

**Issue by ameyagholkar** [adenh93/django-typomatic#56]
👋🏼  @adenh93 

Thanks for this utility! I noticed that you dropped a new release a few days ago. Do you plan to release this onto `pypi` so that we can `pip install` the new versions and test drive it out?

**Comment by adenh93** [comment]
Hey @ameyagholkar,

Very sorry for the late reply 😢 It looks like a previous deployment failed due to some issues with the pypi access token. I'll check this out in the morning and get a release published ASAP!

Thank you!
